services:
  test-db:
    image: postgres
    restart: always
    container_name: dev-test-db
    ports:
      - '6543:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test